# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NativeBridgeLibDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NativeBridgeLibDemo
  pod 'NativeBridgeLib', :path => '../'
  
  # WebViewJavascriptBridge  https://github.com/marcuswestin/WebViewJavascriptBridge
  pod 'WebViewJavascriptBridge', '~> 6.0'
  
  # ZipArchive    https://github.com/ZipArchive/ZipArchive
  pod 'SSZipArchive'
end
